### PR TITLE
Starter Code for Jupyter Notebooks and Markdowns

### PR DESCRIPTION
**Pull request by Nalinc**
This PR addresses #5 and #3.

Markdown files in `markdown/` folder are generated using `nbconvert` from Jupyter notebooks, which themselves have been created using `pandoc` as a base.

- Images have been converted from eps to svg.
- These Jupyter notebooks contain questions from both US and International versions(`uexercise`, `iexercise`).
- Following cross-references are supported.

| Reference Type  | Description | LaTex Syntax* | Markdown Translation | Support |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Page reference  | Refers a page within exercise  |  `\pgref{page-identifier}` | `[page-identifier](#/)`  | Partial (clickable, but doesn't jump)  |
| Chapter reference  | Refers a chapter from textbook | `\chapref{chapter-identifier}`  | `[chapter-identifier](#/)`  | Partial (clickable, but doesn't jump)  |
| Section reference  | Refers a section from textbook | `\secref{section-identifier}`  | `[section-identifier](#/)`  | Partial (clickable, but doesn't jump)  |
| External Figure reference  | Refers an image outside exercise | `\figref{img-identifier}` | `[img-identifier](#/)`  | Partial (clickable, but doesn't jump) |
| Internal Figure reference  | Refers an image embedded within exercises(Figures folder) | `\figref{img-identifier}`  | `[img-identifier](#img-identifier)`  | Full (jump to figure when clicked)  |
| Equation reference  | Refers an equation from textbook | `\eqref{equation-identifier}`  | `[equation-identifier](#/)`  | Partial (clickable, but doesn't jump)  |
| Exercise reference  | Refers to an exercise | `\exref{section-identifier}`  | `[exercise-identifier](#/)`  | Partial (clickable, but doesn't jump) |

* All these LaTeX commands use the same `\ref` command under-the-hood. 

## Manual work involved
(TLDR; a lot)

Having read the book myself, I understand that even a minor styling miss could be catastrophic for readers (P(x), **P**(x), P(**x**) are all different!). Though `pandoc` generated markdowns helped a lot and served as a base for Jupyter notebooks, they were not perfect and needed manual touch. I compared every exercise from all chapters with original book after every conversion and made tweaks accordingly. Following are the tasks that needed manual tweaking.
- **Equations:** Simple equations were fine, but more complicated ones were just giving gibberish. 
- **Tables:** `pandoc` just couldn't generate proper markdown tables from LaTeX, almost everytime!
- **Cross-referencing:** Some references (like `\pgref`) were being missed from `pandoc`. For others (`\figref, \exref`), `pandoc` was not producing clickable links in markdown.
- **Figures:** For some reason, `pandoc` was just ignoring all the images. I had to embed all of them manually.
- **Citations:** Normal `\cite` style citations were being captured by `pandoc`. For others(`\citeA`, `\citeyear`), I had to manually include the references.
- **Question numbering:** `pandoc` was not generating numbers for the questions.  @ansh103 raised a valid point in statement 2(a) of issue #3 that "Can questions numbers be replaced simply by a 'new line', or should we include numbering as in the book". I preferred using numbers because some exercise questions (especially towards the end chapters) were so long that they spanned across multiple paragraphs. Not having any numbering would be confusing and even difficult to manage later.
- Finally, `pandoc` ignores some of the essential macros like `\prog` and `\noprog` which essentially generates "small caps". I had to manually type them because [mathjax doesn't support `\textsc` directly](https://github.com/mathjax/MathJax-docs/wiki/Small-caps-%5Ctextsc-in-MathJaxx).

## Results Comparison:
The following screenshots give a comparison of results between Markdown, Jupyter Notebook and Original text from the book (AIMA 3rd Edition). Click respective figures to view better quality images.

| Comparison Metric | Markdown from pandoc | Jupyter Notebook | AIMA 3rd Edition |
| ------------- | ------------- | ------------- | ------------- |
| Tables | table  | table  | table |
| Equations | equations | equations| equations

Bottomline, we should seriously consider Jupyter notebooks over simple markdown to host aima-exercises because Jupyter can not only provide better support for mathematical equations using MathJax, but also provide more interactivity(running code examples).

Notebooks for aima-exercises(with images) can be viewed at  https://nbviewer.jupyter.org/github/Nalinc/aima-exercises/tree/notebooks/Jupyter%20notebook/
(Github's build-in notebook viewer cannot display images because of relative referencing)

Email: nalin.chhibber@gmail.com

### CODE REVIEW

**Comment by heisenbuug** [comment]
This looks good... @Nalinc if anyways manual work is involved then why not to use markdown?

**Comment by Nalinc** [comment]
@heisenbuug We need to support mathematical equations too and simple markdown cannot do that. MathJax has a great support for equations, but we'd need a separate viewer to visualize them, since Github's markdown parser doesn't support MathJax. That's where Jupyter notebooks enter. Its markdown parser is MathJax aware and it is easy to visualize equations. Good thing is, Github supports Jupyter notebooks(technically, this is not 100% true, but at least you can view your notebooks). This means even if we do not host those Jupyter notebooks externally, they would be accessible on Github in a readable state.

**Comment by heisenbuug** [comment]
@Nalinc I started converting them into markdown...I am in the starting phase so I didn't encountered any maths equation till now. So are you suggesting that I should be converting them into ipynb rather than markdown?

**Comment by Nalinc** [comment]
@heisenbuug not necessarily. You have a bunch of options to tackle such issue.
- Capture screenshots of all equations and embed them as images in markdown, or
- use code blocks to organize your latex equations in markdown.

**Comment by Nalinc** [comment]
@norvig Can you please provide your feedback on this pull request? Where am I lacking, what else needs to be done?

**Comment by norvig** [comment]
This is interesting work. I still don't know what the right answer is. I'm hesitant about notebooks for two reasons: one, it is harder to review edits to them in github, and two, i want exercises to be individually addressable. I'm not sure if that means they are all in separate files, or just that there are links, but as you point out, for unknown reasons, some links make the jump and others don't.

**Pull request merged**
