### PR TITLE
GSoC Updates

### PR DESCRIPTION
**Pull request by sachin10101998**
1) Deleted SASS files and CSS is being managed by public folder.
2) Changed UI Design using Lanyon- A Jekyll theme.
3) Changed answer showing mechanism. All answers submitted by users and community answer are available in the answers directory present alongside each ex folder in all chapters.
4) Updated question.md files for all chapters to accommodate the new UI theme.
5) Comments for each solution are managed and stored inside the useranswers.yaml file.
6) Removed the dependency of AIMA Exercises on Disqus for commenting.
7) Updated the sidebar for easy navigation through the website and added links for new features. 
8) Buttons to hide and view answers/community answer.
9)  Creating the pull request for the master branch and the production site will be live through the GH-pages branch, therefore, the production website will be available throughout the GSOC program. When GSOC will be over the production site can be hosted using the master branch and the GH-pages branch can be deleted.

### CODE REVIEW

**Comment by Nalinc** [comment]
### Possible ways separate submitted answers
 - Github Gists
- Just keep seperate files in answers directory within each exercise.
- Keep a separate answers directory outside the exercises. (_data/)
  - Can we automatically iterate over all .md files in respective answers directory?
  - When a user submits a new answer (newuser-answer.md), it will automatically be visible on page?

- Design considerations for answer submission:
  - Each user submit answer to a separate file
  - Answers should be in the same directory as exercise

- _answers
  - 1-Introduction
    - ex_1
      - sachin_answer.md
      - nalin_answer.md
      - random_answer.md
      - community_answer.md
    - ex_2
  - 2-Intelligent-Agent
  - …

- Keep the same naming convention for answers and markdown. Whenever a chapter name changes, we will make the relevant change in markdown/ and _answers/ directory

**Comment by sachin10101998** [comment]
Bookmarks feature updated in the same PR and question bank serial numbers corrected for all the questions.

**Comment by sachin10101998** [comment]
Sent new PR for lanyon theme feature update only. Should I close this PR?

**Comment by Nalinc** [comment]
Closing as #83 has already been merged!

**Pull request closed without merging**
